FROM openjdk:21-jdk-slim

# Installer psql
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY build/libs/app.jar app.jar

# Script de test + lancement de l'app
COPY entrypoint.sh .

RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]