services:
  - type: web
    name: trainkit-api
    env: java
    rootDir: apps/api
    buildCommand: ./mvnw clean package
    startCommand: java -Dserver.port=$PORT -jar target/trainkit-api-0.0.1-SNAPSHOT.jar
    region: frankfurt
    plan: free
    branch: main